### ISSUE TITLE
"Could not find X's current server!" warnings during player initial connection.

### ISSUE THREAD

**Issue by BlueGuitarCL** [Team-Jackdaw/Essential-PlayerInfo#3]
The title explains the issue by itself. This warning spams up several times, it would been convenient to have some debug option in order to enable it and send you more verbose info. I'll leave here some examples.

__Log:__
```
[00:50:11] [Netty epoll Worker #3/INFO]: [connected player] God_uwuw (/x.x.x.x:57770) has connected
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Netty epoll Worker #3/INFO]: [server connection] God_uwuw -> lobby has connected
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:11] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:12] [Velocity Task Scheduler - #829/WARN]: Could not found God_uwuw's current Server!
[00:50:22] [Netty epoll Worker #3/INFO]: [server connection] God_uwuw -> zmc2 has connected
```
__Console:__
```
[17:00:04 INFO]: [connected player] AngeredMoney529 (/x.x.x.x:0) has connected
[17:00:04 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:04 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 INFO]: [server connection] AngeredMoney529 -> lobby has connected
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
[17:00:05 WARN] [essential-info]: Could not found AngeredMoney529's current Server!
````

**Comment by Lokeyli** [comment]
Thank you for letting us know.

What we are trying to do now is first prevent such warning spamming up since it is not really meaningful but annoying, then we approach the debug option when we are going to work on the command line features.

**Comment by WDRshadow** [comment]
Thank you for your waiting. I think we have fixed this problem in the new commit. You could now download on release.

**Comment by BlueGuitarCL** [comment]
Thanks for the fix! By the way, had to regenerate the config manually. Consider autoupdate for next addition :)

```
[22:21:25 ERROR]: Couldn't pass ProxyInitializeEvent to essential-info
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.moandjiezana.toml.Toml.getBoolean(String)" is null
        at com.jackdaw.essentialinfo.configuration.SettingManager.setUp(SettingManager.java:50) ~[?:?]
        at com.jackdaw.essentialinfo.configuration.SettingManager.<init>(SettingManager.java:42) ~[?:?]
        at com.jackdaw.essentialinfo.EssentialInfo.getSettingManager(EssentialInfo.java:80) ~[?:?]
        at com.jackdaw.essentialinfo.EssentialInfo.onProxyInitialization(EssentialInfo.java:52) ~[?:?]
        at com.jackdaw.essentialinfo.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.1-SNAPSHOT-97.jar:3.1.1-SNAPSHOT (git-2cff5b3b-b97)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.1-SNAPSHOT-97.jar:3.1.1-SNAPSHOT (git-2cff5b3b-b97)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.1-SNAPSHOT-97.jar:3.1.1-SNAPSHOT (git-2cff5b3b-b97)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by WDRshadow** [comment]
Yes, Thanks for your suggession. I have considerated it. The next version will upgrade the config file automaticaly. And it you will see it very soon (maybe tomorrow).

**Comment by BlueGuitarCL** [comment]
I probably should not keep posting issues here but it's just because not having to open new issues for each thing i find. Be free to rename the issue name as you wish.

![image](https://user-images.githubusercontent.com/23057858/156856369-2be67577-6198-4617-a09e-6c1f1cbe14ed.png)
`[23:31:23 INFO]: Loaded plugin essential-info 2.0.0-build-1.3 by Team-Jackdaw`

**Comment by WDRshadow** [comment]
No worry for that. Just free to post anything. I think you may need to set the enable to True to turn on this feature.

**Comment by BlueGuitarCL** [comment]
I apologize, that's fault from my end so no need to worry, now i see it ok ^^
